// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkeiqbpluoovgovrjjfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZWlxYnBsdW9vdmdvdnJqamZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDEwODQsImV4cCI6MjA2NjAxNzA4NH0.QCNSt-6jQvv3VlvsDyYOs0f4O47c4FJoUZxo-wrpsSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});